spring:
  session:
    jdbc:
      initialize-schema: never
  datasource:
    url: jdbc:postgresql://${HOST}:${PORT}/postgres?user=${USER_RW}&password=${PWD_RW}&prepareThreshold=0
    username: ${USER_RW}
    password: ${PWD_RW}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      # This clears any cached prepared statements before reusing the connection.
      connection-init-sql: "DISCARD ALL"
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
  error:
    include-message: always
logging:
  level:
    com.booker_app.backend_service: debug
booking-service:
  secureCookies: false